// Generated by Wrangler on Sun May 19 2024 17:15:41 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CF_PAGES: string;
	CF_PAGES_COMMIT_SHA: string;
	CF_PAGES_BRANCH: string;
	CF_PAGES_URL: string;
}
